# Generated by Django 5.0.1 on 2025-07-29 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="이름")),
                (
                    "japanese_name",
                    models.CharField(max_length=100, verbose_name="일본어 이름"),
                ),
                ("age", models.CharField(max_length=20, verbose_name="나이")),
                ("description", models.TextField(verbose_name="설명")),
                ("personality", models.JSONField(default=list, verbose_name="성격")),
                ("color", models.CharField(max_length=20, verbose_name="대표 색상")),
                ("emoji", models.CharField(max_length=10, verbose_name="이모지")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="characters/",
                        verbose_name="이미지",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "캐릭터",
                "verbose_name_plural": "캐릭터들",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Episode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("description", models.TextField(verbose_name="설명")),
                (
                    "air_date",
                    models.DateField(blank=True, null=True, verbose_name="방영일"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "characters",
                    models.ManyToManyField(
                        related_name="episodes",
                        to="characters.character",
                        verbose_name="등장 캐릭터",
                    ),
                ),
            ],
            options={
                "verbose_name": "에피소드",
                "verbose_name_plural": "에피소드들",
                "ordering": ["-air_date"],
            },
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="대사 내용")),
                ("context", models.TextField(blank=True, verbose_name="상황 설명")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotes",
                        to="characters.character",
                        verbose_name="캐릭터",
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotes",
                        to="characters.episode",
                        verbose_name="등장 에피소드",
                    ),
                ),
            ],
            options={
                "verbose_name": "명대사",
                "verbose_name_plural": "명대사들",
                "ordering": ["-created_at"],
            },
        ),
    ]
