[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["pip install --break-system-packages -r backend/requirements.txt"]

[phases.build]
cmds = ["python backend/manage.py migrate", "python backend/manage.py create_superuser"]

[start]
cmd = "python backend/manage.py runserver 0.0.0.0:$PORT" 