[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.virtualenv"]

[phases.install]
cmds = [
    "python -m venv venv",
    "source venv/bin/activate && pip install -r backend/requirements.txt"
]

[phases.build]
cmds = ["source venv/bin/activate && python backend/manage.py collectstatic --noinput"]

[start]
cmd = "source venv/bin/activate && python backend/manage.py runserver 0.0.0.0:$PORT" 