[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["pip install -r backend/requirements.txt"]

[phases.build]
cmds = ["python backend/manage.py collectstatic --noinput"]

[start]
cmd = "python backend/manage.py runserver 0.0.0.0:$PORT" 