[phases.setup]
nixPkgs = ["python39", "python39Packages.pip", "nodejs", "npm"]

[phases.install]
cmds = [
    "cd backend && pip install -r requirements.txt",
    "cd frontend && npm install"
]

[phases.build]
cmds = [
    "cd backend && python manage.py collectstatic --noinput",
    "cd frontend && npm run build"
]

[start]
cmd = "cd backend && python manage.py runserver 0.0.0.0:$PORT" 