[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["pip install --break-system-packages -r requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = "python manage.py runserver 0.0.0.0:$PORT" 